### PR TITLE
nsc-events-nextjs_20_651_bug-fix-overlap-style-issue-homeeventcard

### LINKED ISSUE #651: Bug: Fix some UI styling issues on HomeEventCard component
As a dev, I want to fix some UI styling issues on the HomeEventCard component, these include:

- a visual issue where there is overlapping of the HomeEventCard component. 
- an issue where the event image can make the height of the card inconsistent.

Also, I will note any additional styling issues found and document them.

Demonstration of these issues: https://imgur.com/YZX6EQe

UPDATE: Issue is a bit tricky to solve, might need help. 

Files to look at: page.tsx (main one, index page, under app), HomeEvents.tsx, HomeEventCard.tsx (All under components)

### PR DESCRIPTION
**Pull request by Asfand00**
## Summary & Changes 📃
- **Resolves:** #651 

- **Summary:** (Briefly describe what this PR does)
  - 🔨 This PR mainly fixes the overlapping issue between the home event cards on the homepage and also an added fix with layout and when users try to input long titles and descriptions.  
  - 👀 The home event cards are a little spaced out to help accommodate the overlapping issue and have better control of the component. When the window shrinks the event cards are no longer overlapping or resizing and are stable for mobile and tablet. When users have long titles or descriptions the event card will accommodate that as well and styles will not break.  
  - 🗨️ Only downside to the long titles and description fix is that the event card will get bigger because of it if the length of those titles and descriptions reach a certain point. This was added because I had noticed while testing that inputting long titles and descriptions will cause truncation and styles breaking with mainly the date getting cutoff and not appearing. If you guys have any suggestions on how to fix this issue I will take it and apply it, otherwise it's something we can come back to if needed.  

Would like feedback on the style changes if anything looks off, something should be removed or added, etc. If something is not clear style wise, I can try to explain it better if it needs more clarification.   

- **Changes:**
  - ✅ Added `spacing={4}` and `sx={{ px: 2 }}` to page.tsx on line 132 
  - ✅ Removed `maxWidth: "700", minHeight: 300, minWidth: { md: 300, lg: 400, xl: 780 }` from top card component as that was the main conflict causing the overlap.
  - ✅ Added `flex: 1 and minWidth: 0` to necessary box and card/cardcontent components to prevent overflow from children
  - ✅ Added style changes to title content and description content (mainly minor). Check the from lines 83 to 157 in the file changes to see all of the inline style changes to each component. Some style changes have comments to describe some of them.  
  - ✅ Added/Removed some minor styles from the tags section block below line 157. 
  - ✅ Added fixed height for cover photo in order to fit the event card at 250 
 
  - 🛠️ Mention breaking changes (if any) - NONE
  - 🔗 Link relevant discussions/issues - NONE
  - 📝 Additional info to assist developers & reviewers - NONE

UPDATE: Modified `HomeEventCard` to `HomeEventsCard` and `HomeEvents` to `HomeEventsList` to keep file consistency

## Screenshots / Visual Aids 🔎
<sub><i>📌 **Required for:** UI changes, layout updates, or bug fixes.</i></sub>

Demo of main overlap fix:
https://github.com/user-attachments/assets/ff1ff111-eb12-45a3-a00a-e3c7f10d449f

Demo of long title and description test:
https://github.com/user-attachments/assets/e6d0b4d5-0519-4871-92e6-0bbd9fab09e2

Screenshot of event picture with fixed size (original is 2000 x 2000 jpeg)
image

## How to Test 🧪
1. **Steps to Reproduce:**
   - Step 1: clone both front-end and back-end branches for nsc events.
   - Step 2: setup .env file on both front and back with mongoDB and have several events (min 4) created on the homepage. Best way to do this is creating sample events in postman (can help if stuck with this step).
   - Step 3: run `npm install` on both front/back 
   - Step 4: start back-end server with `npm run start:dev`
   - Step 5: run front end by entering `npm run dev`
   - Step 6: shrink homepage to see results
   - Step 7 (Optional): create event with long title and description to replicate what you saw in the demo above (Demo of long title and description test). 
2. **Expected Behavior:** The event cards should not be overlapping and are stable when window gets smaller. events with long titles and descriptions are also handled well in the layout.  
3. **Actual Behavior (if bug):** the event cards with long titles and descriptions are handled well but have a small issue with the event card getting bigger, not sure if this can be fixed or not but maybe possible. Possible ticked to be added for next sprint 

## Checklist ✅

- [x] I have **tested** this PR **locally** and it works as expected.
- [x] This PR **resolves an issue** (`Resolves #651`).
- [x] **Reviewers, assignees(self), tags, and labels** are correctly assigned. 
- [x] **Squash commits** and enable **auto-merge** if approved.

### CODE REVIEW

**Review by gitbiruk2010 — APPROVED** [review]
Spacing between event cards looks good on my end and the overlapping issue is gone. 
Test screenshot

image

**Comment by NahomAlemu** [comment]
Well done on fixing the spacing. It is responsive. I've noticed you've renamed the function from ```HomeEventsCard``` to ```HomeEventCard``` was this intentional? If so, you may check, the HomeEvents.tsx file, the function is imported with old name.

**Comment by Asfand00** [comment]
> Well done on fixing the spacing. It is responsive. I've noticed you've renamed the function from `HomeEventsCard` to `HomeEventCard` was this intentional? If so, you may check, the HomeEvents.tsx file, the function is imported with old name.

whoops didn't notice, that wasn't intentional, although maybe we should rename some of our components like `HomeEvents` to `HomeEventsList` to have some consistency. Thanks for catching that.

**Review by TVW96 — CHANGES_REQUESTED** [review]
Great work @Asfand00 , issue fixed however few other bugs here. 

List of bugs:

- Center items in grid view or increase card widths to expand remainder of space 
- Add a maxWidth to keep oversized components from expanding further than 1000px.
- Fix inconsistent padding. (In the screen shot below you can see the green lines that appear only on the right side)
Screenshot 2025-05-07 at 11 00 37 PM
test video: 
https://imgur.com/a/H474OZp

File: app/page.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ import Grid from "@mui/material/Grid";
 import { useTheme } from "@mui/material";
 import { ActivityDatabase } from "@/models/activityDatabase";
 import { useFilteredEvents } from "@/utility/queries";
-import HomeEventCard from "@/components/HomeEventCard";
+import HomeEventsCard from "@/components/HomeEventsCard";
```
Comment (NahomAlemu) [inline app/page.tsx:18]: Here, it was changed from ```HomeEventCard``` to ```HomeEventsCard```

Comment (TVW96) [reply app/page.tsx:18]: @NahomAlemu 
The name change here should be fine as long as the export in the file referenced has the same name.

**Comment by NahomAlemu** [comment]
> UPDATE: actually, it was HomeEventCard before I didn't change it, I thought there was some weird glitch or something on my end but realized later it was already like that I believe (maybe I'm wrong).
> 
You're right, the original file had a naming mismatch. Your change was a fix to make it consistent. 

>  maybe we should rename some of our components like `HomeEvents` to `HomeEventsList` to have some consistency. 

I agree. Below are some components with naming inconsistencies. I'll leave the list here so we can track and address them in future PRs.
| File Name             |  Component Name   | ✅ Suggested Fix                                                           |
| ------------------------ | ------------------- | ------------------------------------------------------------------------- |
| `HomeEventCard.tsx`      | `HomeEventsCard`    | ✅ Rename **component** to `HomeEventCard` OR file to `HomeEventsCard.tsx` |
| `HomeEvents.tsx`         | `HomeEventsList`    | ✅ Rename **file** to `HomeEventsList.tsx`                                 |
| `EventGetter.tsx`        | `EventsList`        | ✅ Rename **file** to `EventsList.tsx`                                     |
| `InputFields.tsx`        | `InputField`        | ✅ Rename **file** to `InputField.tsx`                                     |
| `ViewMyEventsGetter.tsx` | `MyEventsList`      | ✅ Rename **file** to `MyEventsList.tsx`                                   |
| `WrapperDiv.tsx`         | `CustomCardContent` | ✅ Rename **file** to `CustomCardContent.tsx` OR component to `WrapperDiv` |

**Comment by TVW96** [comment]
@bennettsf @Asfand00 @NahomAlemu 
My apologies, issue is fixed here. I needed to refresh my local once more. 

I did though sort of appreciate the grid view with 3 or so cards per row. Having only the 2 cards in each row make the page seem to formatted and dull. What do you all think about further readjusting the page so that we can get a responsive design that is both fluid but also dynamic. As I see it right now the page is responsive but is lacking dynamism due to the restrictive row limits. 

https://github.com/user-attachments/assets/d3d2e83d-eb96-424c-9c5a-3342f8255937

**Comment by TVW96** [comment]
@NahomAlemu 

You should try wiping the folder from your local machine and then recloning in vscode terminal.

**Review by TVW96 — APPROVED** [review]

**Comment by Asfand00** [comment]
> @TVW96 I'm not getting that bug you posted, mine looks fine. It would be nice however to add a bit larger x-margin on the smaller screen size so they don't go out all the way to the edge.
> 
>  78fJ4SO.mp4

True i did wonder about that, good point I'll add some more margins on the smaller screens. @bennettsf

**Comment by Asfand00** [comment]
> @bennettsf @Asfand00 @NahomAlemu My apologies, issue is fixed here. I needed to refresh my local once more.
> 
> I did though sort of appreciate the grid view with 3 or so cards per row. Having only the 2 cards in each row make the page seem to formatted and dull. What do you all think about further readjusting the page so that we can get a responsive design that is both fluid but also dynamic. As I see it right now the page is responsive but is lacking dynamism due to the restrictive row limits.
> 
>  Test2.mov

it's worth considering, I'd like @bennettsf and @NahomAlemu opinions on this too, I personally like the 2 per row, I think in my opinion it's a little better because if we add 3 per row, the event cards will be smaller and therefore if there's a long title or description the event card will either have truncated information which will force users to see more details on it rather than on the homepage or the event cards will get stretched to fit information. If we implement the 3 per row, we will need to resize the fonts as well and shorten some of the card components to fit better.

File: app/page.tsx (hunk 1 above)
Comment (Asfand00) [reply app/page.tsx:18]: yeah, I updated those appropriately and tested them to make sure all imports were fine and updated accordingly. It was done for the consistent naming basis for the component.

**Review by NahomAlemu — APPROVED** [review]

**Review by Bejarano03 — COMMENTED** [review]
LGTM, great work on getting this bug fixed. I found this helped a lot in making sure the styling was done correctly.
